#pragma once

/*
 * PluginScopeAudioProcessorEditor - TEMPLATE FILE
 *
 * Generated by: ui-finalization-agent
 * Mockup version: v1
 * Generated date: 2026-02-19
 *
 * PURPOSE:
 *   This is a TEMPLATE for gui-agent reference during Stage 3 (GUI) implementation.
 *   gui-agent will adapt this to the actual plugin structure. Do NOT copy-paste
 *   without reviewing the class name, constructor signature, and member order.
 *
 * PARAMETER SUMMARY (5 AudioParameterChoice):
 *   view_mode      -> WebComboBoxRelay  (0=Simplified, 1=Expert)
 *   analysis_mode  -> WebComboBoxRelay  (0=Live, 1=Snapshot)
 *   analysis_type  -> WebComboBoxRelay  (0=Freq, 1=Dynamics, 2=Distortion, 3=Phase, 4=Latency)
 *   test_signal    -> WebComboBoxRelay  (0=Sine Sweep, 1=White Noise, 2=Pink Noise, 3=Impulse, 4=Live Audio)
 *   comparison     -> WebComboBoxRelay  (0=Off, 1=A/B Plugins, 2=Before-After)
 *
 * MEMBER ORDER (CRITICAL — DO NOT REORDER):
 *   Destruction order is reverse of declaration order.
 *   Attachments call evaluateJavascript() during destruction, so they MUST
 *   be declared AFTER webView (destroyed before webView).
 *   Order: relays -> webView -> attachments
 *
 * WEBVIEW NOTES:
 *   - HTML resource served from BinaryData (index_html / index_html_size)
 *   - Resource provider handles MIME types for all assets
 *   - C++ -> JS: webView->evaluateJavascript("handleParameterChanged('id', index)", ...)
 *   - JS -> C++: window.__JUCE__.backend.emitEvent('eventName', data)
 *     handled via WebBrowserComponent::Options::withNativeFunction()
 */

#include <JuceHeader.h>

// Forward declaration
class PluginScopeAudioProcessor;


class PluginScopeAudioProcessorEditor  : public juce::AudioProcessorEditor
{
public:
    explicit PluginScopeAudioProcessorEditor (PluginScopeAudioProcessor&);
    ~PluginScopeAudioProcessorEditor() override;

    //==========================================================================
    void paint (juce::Graphics&) override;
    void resized() override;

private:
    //==========================================================================
    // Reference to processor (no ownership — must come first)
    PluginScopeAudioProcessor& audioProcessor;

    //==========================================================================
    // *** CRITICAL MEMBER DECLARATION ORDER ***
    //
    // Members are destroyed in REVERSE order of declaration.
    //
    // Correct order:
    //   1. Relays FIRST  (no dependencies — safe to destroy last)
    //   2. WebView SECOND (depends on relays)
    //   3. Attachments LAST (depend on relays AND webView — destroyed FIRST)
    //
    // Wrong order causes: attachments call evaluateJavascript() on a
    // destroyed WebView -> undefined behaviour -> crash in release builds.
    //==========================================================================

    // 1. RELAYS FIRST (no dependencies)
    std::unique_ptr<juce::WebComboBoxRelay> viewModeRelay;
    std::unique_ptr<juce::WebComboBoxRelay> analysisModeRelay;
    std::unique_ptr<juce::WebComboBoxRelay> analysisTypeRelay;
    std::unique_ptr<juce::WebComboBoxRelay> testSignalRelay;
    std::unique_ptr<juce::WebComboBoxRelay> comparisonRelay;

    // 2. WEBVIEW SECOND (depends on relays via .withOptionsFrom())
    std::unique_ptr<juce::WebBrowserComponent> webView;

    // 3. ATTACHMENTS LAST (depend on relays AND webView — destroyed first)
    std::unique_ptr<juce::WebComboBoxParameterAttachment> viewModeAttachment;
    std::unique_ptr<juce::WebComboBoxParameterAttachment> analysisModeAttachment;
    std::unique_ptr<juce::WebComboBoxParameterAttachment> analysisTypeAttachment;
    std::unique_ptr<juce::WebComboBoxParameterAttachment> testSignalAttachment;
    std::unique_ptr<juce::WebComboBoxParameterAttachment> comparisonAttachment;

    //==========================================================================
    // Resource provider
    // Returns BinaryData resources to the WebView by URL path.
    juce::WebBrowserComponent::Resource getResource (const juce::String& url);

    //==========================================================================
    // Native function handler
    // Handles events emitted by JavaScript via window.__JUCE__.backend.emitEvent()
    void handleNativeEvent (const juce::var& eventData);

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PluginScopeAudioProcessorEditor)
};
