/*
 * PluginScopeAudioProcessorEditor - TEMPLATE FILE (Implementation)
 *
 * Generated by: ui-finalization-agent
 * Mockup version: v1
 * Generated date: 2026-02-19
 *
 * INITIALIZATION ORDER (must match declaration order in .h):
 *   1. Relays created in initializer list
 *   2. webView constructed with Options that reference all relays
 *   3. Attachments created in initializer list (after webView)
 *
 * IMPORTANT NOTES FOR gui-agent:
 *   - Replace "PluginScopeAudioProcessor" with actual processor class name
 *   - Replace "index_html" / "index_html_size" with actual BinaryData symbols
 *     (Symbol name depends on CMakeLists juce_add_binary_data SOURCES entry filename)
 *   - The BinaryData symbol for "index.html" becomes "BinaryData::index_html"
 *     and its size "BinaryData::index_html_size"
 *   - webView size is set by setSize() in constructor body — matches YAML: 1100x650
 *   - Min size enforced in resized() using ComponentBoundsConstrainer (optional)
 *   - All 5 parameters are AudioParameterChoice — use WebComboBoxParameterAttachment
 *   - The JS function handleParameterChanged(paramId, index) is the C++ -> JS bridge
 *
 * THREAD SAFETY:
 *   evaluateJavascript() must be called on the message thread.
 *   If notifying from audio thread, use MessageManager::callAsync().
 */

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
PluginScopeAudioProcessorEditor::PluginScopeAudioProcessorEditor (PluginScopeAudioProcessor& p)
    : AudioProcessorEditor (&p),
      audioProcessor (p),

      //------------------------------------------------------------------------
      // 1. RELAYS FIRST — create before webView
      //    Parameter ID strings MUST exactly match APVTS parameter IDs.
      //    The string passed to WebComboBoxRelay IS the parameter ID.
      //------------------------------------------------------------------------
      viewModeRelay     (std::make_unique<juce::WebComboBoxRelay> ("view_mode")),
      analysisModeRelay (std::make_unique<juce::WebComboBoxRelay> ("analysis_mode")),
      analysisTypeRelay (std::make_unique<juce::WebComboBoxRelay> ("analysis_type")),
      testSignalRelay   (std::make_unique<juce::WebComboBoxRelay> ("test_signal")),
      comparisonRelay   (std::make_unique<juce::WebComboBoxRelay> ("comparison")),

      //------------------------------------------------------------------------
      // 2. WEBVIEW SECOND — constructed with Options referencing all relays
      //    .withOptionsFrom() registers each relay with the WebView backend.
      //    Order of .withOptionsFrom() calls does not matter.
      //------------------------------------------------------------------------
      webView (std::make_unique<juce::WebBrowserComponent> (
          juce::WebBrowserComponent::Options{}
              .withBackend (juce::WebBrowserComponent::Options::Backend::webview2)
              .withWinWebView2Options (
                  juce::WebBrowserComponent::Options::WinWebView2{}.withUserDataFolder (
                      juce::File::getSpecialLocation (juce::File::tempDirectory)))
              .withResourceProvider (
                  [this] (const auto& url) { return getResource (url); },
                  juce::URL {"https://pluginscope.localhost/"})
              .withNativeFunction (
                  "pluginscopeEvent",
                  [this] (const juce::Array<juce::var>& args, juce::WebBrowserComponent::NativeFunctionCompletion completion)
                  {
                      if (args.size() > 0)
                          handleNativeEvent (args[0]);
                      completion ("ok");
                  })
              // Register all 5 relays with the WebView
              .withOptionsFrom (*viewModeRelay)
              .withOptionsFrom (*analysisModeRelay)
              .withOptionsFrom (*analysisTypeRelay)
              .withOptionsFrom (*testSignalRelay)
              .withOptionsFrom (*comparisonRelay)
      )),

      //------------------------------------------------------------------------
      // 3. ATTACHMENTS LAST — created after relays AND webView exist
      //    WebComboBoxParameterAttachment(parameter, relay)
      //    The parameter pointer is obtained via APVTS::getParameter(id).
      //    Cast: dynamic_cast or static_cast to RangedAudioParameter* is fine.
      //------------------------------------------------------------------------
      viewModeAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.apvts.getParameter ("view_mode"),
          *viewModeRelay)),

      analysisModeAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.apvts.getParameter ("analysis_mode"),
          *analysisModeRelay)),

      analysisTypeAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.apvts.getParameter ("analysis_type"),
          *analysisTypeRelay)),

      testSignalAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.apvts.getParameter ("test_signal"),
          *testSignalRelay)),

      comparisonAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.apvts.getParameter ("comparison"),
          *comparisonRelay))
{
    addAndMakeVisible (*webView);

    // Navigate to the embedded resource root.
    // The resource provider handles "https://pluginscope.localhost/index.html"
    webView->goToURL ("https://pluginscope.localhost/index.html");

    // Default window size from YAML: 1100 x 650
    // The plugin can be resized down to 900 x 520 (enforced via constrainer).
    setSize (1100, 650);
    setResizable (true, true);

    // Optional: enforce min/max resize bounds
    auto* constrainer = getConstrainer();
    if (constrainer != nullptr)
    {
        constrainer->setMinimumSize (900, 520);
        constrainer->setMaximumSize (2560, 1600);
    }
}

//==============================================================================
PluginScopeAudioProcessorEditor::~PluginScopeAudioProcessorEditor()
{
    // Destructor body intentionally empty.
    // Member destruction order (reverse of declaration):
    //   comparisonAttachment, testSignalAttachment, analysisTypeAttachment,
    //   analysisModeAttachment, viewModeAttachment  (attachments destroyed first)
    //   webView                                      (then webView)
    //   comparisonRelay, testSignalRelay, analysisTypeRelay,
    //   analysisModeRelay, viewModeRelay             (relays destroyed last)
}

//==============================================================================
void PluginScopeAudioProcessorEditor::paint (juce::Graphics& g)
{
    // Background matches CSS --bg: #121212
    g.fillAll (juce::Colour (0xff121212));
}

//==============================================================================
void PluginScopeAudioProcessorEditor::resized()
{
    // WebView fills the entire editor window.
    // The HTML/CSS handles all internal layout using percentage-based flexbox.
    webView->setBounds (getLocalBounds());
}

//==============================================================================
// Resource provider — called by WebBrowserComponent when JS requests a URL.
// Returns the HTML/JS/CSS content from BinaryData (embedded at compile time).
//
// MIME types reference:
//   .html  -> "text/html"
//   .js    -> "application/javascript"   (NOT text/javascript — use MIME standard)
//   .css   -> "text/css"
//   .png   -> "image/png"
//   .svg   -> "image/svg+xml"
//   .woff2 -> "font/woff2"
//
// NOTE FOR gui-agent:
//   The BinaryData symbol name is derived from the source filename in CMakeLists.
//   "Source/ui/public/index.html" -> BinaryData::index_html / BinaryData::index_html_size
//   "Source/ui/public/js/juce/index.js" -> BinaryData::index_js / BinaryData::index_js_size
//   (juce_add_binary_data strips path components and replaces . and / with _)
//==============================================================================
juce::WebBrowserComponent::Resource
PluginScopeAudioProcessorEditor::getResource (const juce::String& url)
{
    // Strip query parameters and leading slash
    auto path = juce::URL (url).getSubPath().trimCharactersAtStart ("/");

    if (path.isEmpty() || path == "index.html")
    {
        return { std::vector<std::byte> (
                     reinterpret_cast<const std::byte*> (BinaryData::index_html),
                     reinterpret_cast<const std::byte*> (BinaryData::index_html)
                         + BinaryData::index_html_size),
                 "text/html" };
    }

    if (path == "js/juce/index.js")
    {
        return { std::vector<std::byte> (
                     reinterpret_cast<const std::byte*> (BinaryData::juce_index_js),
                     reinterpret_cast<const std::byte*> (BinaryData::juce_index_js)
                         + BinaryData::juce_index_js_size),
                 "application/javascript" };
    }

    // Return empty optional for unknown paths (404)
    return {};
}

//==============================================================================
// Native event handler — called when JavaScript fires:
//   window.__JUCE__.backend.emitEvent('pluginscopeEvent', data)
//
// Expected event data format (juce::var object):
//   { "type": "parameterChanged", "id": "view_mode", "index": 0 }
//   { "type": "analyzeRequested", "testSignal": 0, "analysisType": 0 }
//   { "type": "loadPluginRequested" }
//   { "type": "exportRequested" }
//
// NOTE FOR gui-agent:
//   The 'parameterChanged' branch is handled automatically by
//   WebComboBoxParameterAttachment (via the relay). You only need to handle
//   custom non-parameter events here (analyzeRequested, loadPluginRequested, etc.)
//==============================================================================
void PluginScopeAudioProcessorEditor::handleNativeEvent (const juce::var& eventData)
{
    if (!eventData.isObject())
        return;

    auto* obj = eventData.getDynamicObject();
    if (obj == nullptr)
        return;

    auto type = obj->getProperty ("type").toString();

    if (type == "analyzeRequested")
    {
        // Trigger analysis in the processor.
        // Implementation depends on PluginScopeAudioProcessor API.
        // Example: audioProcessor.triggerAnalysis();
        juce::ignoreUnused (type);
    }
    else if (type == "loadPluginRequested")
    {
        // Open plugin scanner dialog.
        // Implementation: audioProcessor.openPluginBrowser() or similar.
        juce::ignoreUnused (type);
    }
    else if (type == "exportRequested")
    {
        // Export current analysis results.
        // Implementation: audioProcessor.exportResults() or similar.
        juce::ignoreUnused (type);
    }
}

//==============================================================================
// C++ -> JS notification helper (example usage)
//
// Call this from the message thread when analysis data is ready.
// Example:
//
//   void PluginScopeAudioProcessorEditor::notifyAnalysisComplete (const AnalysisResult& result)
//   {
//       juce::String js = "handleAnalysisComplete(" + result.toJSON() + ");";
//       webView->evaluateJavascript (js, [] (juce::WebBrowserComponent::EvaluationResult) {});
//   }
//
// If calling from the audio thread, use:
//   juce::MessageManager::callAsync ([this, js] { webView->evaluateJavascript (js, {}); });
//
// The JS function handleAnalysisComplete() must be defined in index.html.
//==============================================================================
